### ISSUE TITLE
repeated make clean should not show error

### ISSUE THREAD

**Issue by TsinghuaRoger** [pingcap-incubator/tinysql#132]
Repeat "make clean" should not show error

**Comment by TsinghuaRoger** [comment]
$make clean
GO111MODULE=on go clean -i ./...
rm -rf *.out
cd parser && make clean
go clean -i ./...
rm -rf *.out
rm parser.go
rm: parser.go: No such file or directory
make[1]: *** [clean] Error 1
make: *** [clean] Error 2

**Comment by yanguwan** [comment]
solved in pr repeated "make clean" silently #133
