### ISSUE TITLE
proj2: parser_test directly success without any changing.

### ISSUE THREAD

**Issue by Yisaer** [pingcap-incubator/tinysql#29]
When I start proj2, parser_test directly success without any changing.

**Comment by SenZhangAI** [comment]
I've tested it. It failed before I wrote some code in `parer/parser.y` and then generated `parser/parser.go`

I think you may not test `func (s *testParserSuite) TestDMLStmt(c *C)`

**Comment by Yisaer** [comment]
@SenZhangAI  Thanks for mentioning, the problem has already been fixed now. I will close this issue.
